import Link from 'next/link';
import Control from './Control';
import './globals.css';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const res = await fetch(process.env.NEXT_PUBLIC_API_URL+'/topics');
  const topics = await res.json();

  return (
    <html>
      <body>
        <h1>
          <a href="/">WEB</a>
        </h1>
        <ol>
          {topics.map(topic => <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>)}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}
